In [2]:
import pandas as pd
import fastparquet
import openpyxl
import os
import numpy as np
from geopy.distance import geodesic
from geopy.geocoders import Nominatim

In [10]:
hr_mapping = {
    'id' : np.int32 ,
    'last_name'  :object,
    'first_name' : object,
    'birthday' : None,
    'business_unit' : object,
    'entry_date' : None,
    'salary' : np.float64,
    'employement contract' :object,
    'vacation_days': np.int32,
    'address' : object,
    'transport_mode' : object,
    'choice' : object
}
hr_names = hr_mapping.keys()

In [11]:
df_rh = pd.read_excel("../sources/Fusion.xlsx", names= list(hr_names), dtype= hr_mapping  )
df_rh

,id,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode,choice
0,86847,Arnaud,Jeremy,1989-05-13,Support,2020-03-31,29180.0,CDI,28,"139 Av. des Pins, 34150 Gignac",véhicule thermique/électrique,Football
1,92368,Torres,Emmanuelle,2001-06-25,Marketing,2020-04-21,74310.0,CDI,28,"Pl. de la Liberté, 34470 Pérols",Vélo/Trottinette/Autres,Runing
2,91916,Legrand,Margaud,1983-10-13,Finance,2020-05-19,47530.0,CDI,27,"72 Rue des Pins, 34470 Pérols",Vélo/Trottinette/Autres,Rugby
3,36913,Pons,Brigitte,1977-12-27,Finance,2020-05-26,59790.0,CDI,28,"169 Rue Jean Jaures, 34730 Prades-le-Lez",Transports en commun,0
4,79837,Muller,Alphonse,1970-12-10,Ventes,2020-05-26,30360.0,CDI,27,"11 Lot. Mas de Combes, 34230 Popian",véhicule thermique/électrique,0
...,...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910.0,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing
157,41377,Faure,Emmanuelle,1998-06-16,Support,2025-03-05,52920.0,CDI,25,"Rue du Ctre, 34160 Saint-Drézéry",véhicule thermique/électrique,Football
158,43015,Mendes,Juliette,1991-10-22,Support,2025-03-06,57040.0,CDI,26,"199-97 Av. du Pichagret, 34980 Saint-Gély-du-Fesc",véhicule thermique/électrique,0
159,19773,Fischer,Benoit,1981-03-31,Support,2025-03-24,62670.0,CDI,25,"110 Rue de la République, 34000 Montpellier",véhicule thermique/électrique,0
160,27620,Hebert,William,1973-03-10,Ventes,2025-03-24,68120.0,CDI,25,"18 Rue des Vignes, 34970 Lattes",Vélo/Trottinette/Autres,0

In [62]:
df_rh.dtypes

id                               int32
last_name                       object
first_name                      object
birthday                datetime64[us]
business_unit                   object
entry_date              datetime64[us]
salary                         float64
employement contract            object
vacation_days                    int32
address                         object
transport_mode                  object
dtype: object

,id,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940.0,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360.0,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390.0,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320.0,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870.0,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running
...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910.0,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430.0,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380.0,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170.0,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180.0,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres

In [ ]:
print("--- Analyse géographique des déplacements ---")
geolocator = Nominatim(user_agent="sport_pipeline_poc")
company_address = "1362 Av. des Platanes, 34970 Lattes"
location_comp = geolocator.geocode(company_address)
coords_company = (location_comp.latitude, location_comp.longitude)
coords_company

--- Analyse géographique des déplacements ---

In [32]:
dup = df_rh.duplicated("transport_mode")

In [51]:
dup_tm = df_rh[~dup]["transport_mode"].to_list()
dup_tm

['Transports en commun',
 'véhicule thermique/électrique',
 'Marche/running',
 'Vélo/Trottinette/Autres']

In [ ]:
#df_sport = pd.read_excel("../sources/Fusion.xlsx", sheet_name= "Feuille2", names=['id',"sport_type"])
df_sport = pd.read_excel("../sources/Fusion.xlsx", sheet_name= "Feuille2", names=['id',"sport_type"])
df_sport

        id sport_type
0    12497        NaN
1    13064        NaN
2    13780        NaN
3    15493        NaN
4    16872        NaN
..     ...        ...
156  96558  Triathlon
157  96902        NaN
158  97309     Tennis
159  99401     Runing
160  99514        NaN

[161 rows x 2 columns]

In [32]:
df_merge = pd.read_parquet("../kestra/tmp/merge.parquet")
df_merge

,id,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode,distance_kms,margin_kms,sport_type
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940.0,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun,0.0,0.0,None
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360.0,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique,0.0,0.0,None
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390.0,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique,0.0,0.0,Tennis
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320.0,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,0.0,15.0,None
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870.0,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,0.0,15.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910.0,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,0.0,25.0,Course à pied
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430.0,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,0.0,15.0,Tennis
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380.0,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique,0.0,0.0,Course à pied
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170.0,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique,0.0,0.0,None
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180.0,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,0.0,25.0,Natation

In [26]:
df_sport['sport_type'].notna().sum()
df_test = df_sport.merge(df_merge, how= 'left', on="id", indicator=True)
df_test

,id,sport_type,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode,distance_kms,margin_kms,_merge
0,12497,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,13064,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,13780,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,15493,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,16872,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,96558,Triathlon,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
157,96902,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
158,97309,Tennis,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
159,99401,Runing,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
160,99514,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [27]:
df_extra_sports = df_test[df_test['_merge'] == 'left_only']
df_extra_sports

,id,sport_type,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode,distance_kms,margin_kms,_merge
0,12497,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,13064,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,13780,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,15493,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,16872,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,96558,Triathlon,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
157,96902,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
158,97309,Tennis,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
159,99401,Runing,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
160,99514,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [35]:
df_extra_sports.loc[156,"id"]

np.int64(96558)

In [34]:
df_extra_declared_sports = df_extra_sports[df_extra_sports['sport_type'].notnull()]
df_extra_declared_sports.columns.to_list()

['id',
 'sport_type',
 'last_name',
 'first_name',
 'birthday',
 'business_unit',
 'entry_date',
 'salary',
 'employement contract',
 'vacation_days',
 'address',
 'transport_mode',
 'distance_kms',
 'margin_kms',
 '_merge']

In [82]:
sports = pd.read_excel('../sources/contexte/Données_Fusion.xlsx', sheet_name= "Feuille3")

In [84]:
sports.to_json("sports.json")