In [68]:
import pandas as pd
import fastparquet
import openpyxl
import os
import numpy as np
from geopy.distance import geodesic
from geopy.geocoders import Nominatim

In [60]:
hr_mapping = {
    'id' : np.int32 ,
    'last_name'  :object,
    'first_name' : object,
    'birthday' : None,
    'business_unit' : object,
    'entry_date' : None,
    'salary' : np.float64,
    'employement contract' :object,
    'vacation_days': np.int32,
    'address' : object,
    'transport_mode' : object,
}
hr_names = hr_mapping.keys()

In [61]:
df_rh = pd.read_excel("/home/yves/Documents/DEV/OCDE/OCDE-P12/data/sources/Données+RH.xlsx", names= list(hr_names), dtype= hr_mapping
                      )

In [62]:
df_rh.dtypes

id                               int32
last_name                       object
first_name                      object
birthday                datetime64[us]
business_unit                   object
entry_date              datetime64[us]
salary                         float64
employement contract            object
vacation_days                    int32
address                         object
transport_mode                  object
dtype: object

In [63]:
df_rh

,id,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940.0,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360.0,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390.0,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320.0,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870.0,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running
...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910.0,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430.0,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380.0,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170.0,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180.0,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres

In [54]:
print("--- Analyse géographique des déplacements ---")
geolocator = Nominatim(user_agent="sport_pipeline_poc")
company_address = "1362 Av. des Platanes, 34970 Lattes"
location_comp = geolocator.geocode(company_address)
coords_company = (location_comp.latitude, location_comp.longitude)

--- Analyse géographique des déplacements ---

In [55]:
coords_company

(43.589971, 3.913169)

In [32]:
dup = df_rh.duplicated("transport_mode")

In [51]:
dup_tm = df_rh[~dup]["transport_mode"].to_list()
dup_tm

['Transports en commun',
 'véhicule thermique/électrique',
 'Marche/running',
 'Vélo/Trottinette/Autres']

In [64]:
df_rh.to_csv("RH.csv")

In [66]:
dfcsv = pd.read_csv("RH.csv")
dfcsv.dtypes

Unnamed: 0                int64
id                        int64
last_name                   str
first_name                  str
birthday                    str
business_unit               str
entry_date                  str
salary                  float64
employement contract        str
vacation_days             int64
address                     str
transport_mode              str
dtype: object

In [67]:
dfcsv

,Unnamed: 0,id,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode
0,0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940.0,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun
1,1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360.0,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique
2,2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390.0,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique
3,3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320.0,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running
4,4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870.0,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running
...,...,...,...,...,...,...,...,...,...,...,...,...
156,156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910.0,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres
157,157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430.0,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running
158,158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380.0,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique
159,159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170.0,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique
160,160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180.0,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres

In [73]:
df2 = pd.read_parquet('../kestra/tmp/rh_processed.parquet')
df2

,id,last_name,first_name,birthday,business_unit,entry_date,salary,employement contract,vacation_days,address,transport_mode,distance_kms,margin_kms
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940.0,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun,0.00,0.00
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360.0,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique,0.00,0.00
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390.0,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique,0.00,0.00
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320.0,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,1.73,13.27
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870.0,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,0.83,14.17

In [79]:
mask = df2['transport_mode'].isin(['Marche/running'])

In [80]:
print(df2[mask].shape)

(2, 13)

In [82]:
sports = pd.read_excel('../sources/contexte/Données_Fusion.xlsx', sheet_name= "Feuille3")

In [84]:
sports.to_json("sports.json")

In [85]:
sp = pd.read_json("../data/sources/sports.json")

In [88]:
list(sp['Sport'])

['Course à pied',
 'Trail',
 'Marche',
 'Randonnée',
 'Course à pied virtuelle',
 'Vélo',
 'Sortie en VTT',
 'Sortie en gravel',
 'Sortie à vélo électrique',
 'VTT électrique',
 'Vélomobile',
 'Vélo virtuel',
 'Canoë',
 'Kayak',
 'Kitesurf',
 'Aviron',
 'Stand up paddle',
 'Surf',
 'Natation',
 'Windsurf',
 'Patin à glace',
 'Ski alpin',
 'Ski de randonnée',
 'Ski nordique',
 'Snowboard',
 'Raquettes',
 'Handbike ',
 'Roller ',
 'Escalade ',
 'Ski à roulettes ',
 'Golf ',
 'Skateboard ',
 'Football ',
 'Course en fauteuil ',
 'Badminton ',
 'Tennis ',
 'Pickleball ',
 'Crossfit ',
 'Elliptique ',
 "Simulateur d'escalier ",
 'Entraînement aux poids ',
 'Yoga ',
 'Entraînement ',
 'HIIT ',
 'Pilates ',
 'Tennis de table ',
 'Squash ',
 'Racquetball ']